#!/bin/sh
# Reconstructs `Secrets.xcconfig` from Xcode Cloud environment variables.
#
# Background: secrets live in a gitignored `Secrets.xcconfig` at the repo
# root (see project_cafehunter_secrets memory; GMS_PLACES_API_KEY rotated
# after the 2026-05-21 leak). Xcode Cloud clones the repo from GitHub and
# therefore doesn't have the file — the Xcode project's base configuration
# reference fails to resolve and the build aborts with:
#
#   Unable to open base configuration reference file 'Secrets.xcconfig'
#
# This script runs in the post-clone phase (before resolving SPM packages
# or building) and writes the file from the env var set in App Store
# Connect → Xcode Cloud → Workflow → Environment Variables. The env var
# MUST be flagged as "Secret" so it's redacted in build logs.

set -e

if [ -z "$GMS_PLACES_API_KEY" ]; then
  echo "ERROR: GMS_PLACES_API_KEY env var is empty. Set it in App Store"
  echo "       Connect → Xcode Cloud → Workflow → Environment Variables."
  exit 1
fi

cat > "$CI_WORKSPACE/Secrets.xcconfig" <<EOF
// AUTO-GENERATED by ci_scripts/ci_post_clone.sh — do not commit.
// Sourced from Xcode Cloud's GMS_PLACES_API_KEY environment variable.
GMS_PLACES_API_KEY = $GMS_PLACES_API_KEY
EOF

echo "ci_post_clone: wrote Secrets.xcconfig (key length: ${#GMS_PLACES_API_KEY})"
